### ISSUE TITLE
Enable math functions

### ISSUE THREAD

**Issue by johannesgerer** [IreneKnapp/direct-sqlite#100]
I guess having at least a flag to turn on [math functions](https://www.sqlite.org/lang_mathfunc.html) like `sqrt` would be very useful.

**Comment by jchia** [comment]
I've added a flag to enable built-in math functions.

**Comment by johannesgerer** [comment]
Great, thank you. After looking into it a bit more, I found that the 'default' Sqlite binary for windows and in most Linux distributions has many flags enabled by default.

The way they become activated (I guess) is because the sqlite make files are used which enable them. 
For example for [windows](https://sqlite.org/src/file?name=Makefile.msc&ci=trunk) or [linux](https://sqlite.org/src/file?name=configure&ci=trunk)

Not sure whether this library should try to use them as a default, just wanted to mention this for future reference.

**Comment by jchia** [comment]
Which Linux distros has enabled the built-in math functions for their packaged sqlite? Ubuntu 20.04 is not one of them.
