### ISSUE TITLE
Add built-tool-depends hsc2hs?

### ISSUE THREAD

**Issue by moll** [IreneKnapp/direct-sqlite#101]
Hey,

If I'm not mistaken, shouldn't `direct-sqlite.cabal` contain a reference to `hsc2hs`? There is a `Types.hsc` file in the repo, after all. I stumbled upon this seeing the following error from the [Haskell Language Server](https://github.com/haskell/haskell-language-server)/[HIE BIOS](https://github.com/haskell/hie-bios):

> cabal-3.6.2.0: The program 'hsc2hs' is required but it could not be found.

Regular compiling via Cabal works, of course, but perhaps because Cabal deduces more than HLS/HIE BIOS.

Anywho, throwing the following to `direct-sqlite.cabal` seems to have fixed the problem:
```
build-tool-depends: hsc2hs:hsc2hs
```

**Comment by jchia** [comment]
I'm not sure. I wonder what other projects on Hackage do that also use hsc2hs.

hsc2hs is distributed together with GHC in the binary distribution package.

**Comment by moll** [comment]
Given we also add explicit dependencies to packages also distributed with GHC, it makes sense to explicitly list build tools it includes.

However, GitHub search shows plenty of packages referencing `hsc2hs`: https://github.com/search?q=build-tool-depends+hsc2hs+path%3A*.cabal&type=code&ref=advsearch

That includes Stack, the package manager: https://github.com/commercialhaskell/stack/blob/87c1a5b7d309b6b752dd3b39307abdf0d8f68438/stack.cabal#L635
