### ISSUE TITLE
Sqlite backup functions support

### ISSUE THREAD

**Issue by satvikc** [IreneKnapp/direct-sqlite#27]
sqlite3_backup_finish
    sqlite3_backup_init 
    sqlite3_backup_pagecount
    sqlite3_backup_remaining
    sqlite3_backup_step

**Comment by nurpax** [comment]
@satvikc This support just got merged in https://github.com/IreneKnapp/direct-sqlite/pull/58.  It's been a while since you asked but it's in now :)

**Comment by nurpax** [comment]
direct-sqlite-2.3.15 is now available on Hackage with the requested functionality.
