### ISSUE TITLE
Any need to apply stat64 workaround?

### ISSUE THREAD

**Issue by joncfoo** [IreneKnapp/direct-sqlite#70]
[This ticket](https://ghc.haskell.org/trac/ghc/ticket/7072) seems to suggest the `stat64` workaround is no longer needed since GHC 7.8.1

I ran across this while updating sqlite in persistent-sqlite.

**Comment by IreneKnapp** [comment]
Great question. Somebody on a Mac will need to test it.

**Comment by nurpax** [comment]
Thanks for the tip!  I updated to the latest sqlite3 on my Mac and the build worked fine without the stat64 WAR.

**Comment by joncfoo** [comment]
FYI I modifed the wiki - https://github.com/IreneKnapp/direct-sqlite/wiki/Hacking
