### ISSUE TITLE
Inaccurate version bound / build failure for GHC < 7.10

### ISSUE THREAD

**Issue by hvr** [IreneKnapp/direct-sqlite#78]
As you can see at https://matrix.hackage.haskell.org/package/direct-sqlite@1550399426 the most recent direct-sqlite release failed to build on GHC 7.8 and older due to `<$>` not being in scope. This had a wide ranging fallout as it effectively broke all default-computed build-plans for those GHC versions that depend on `direct-sqlite`, such as e.g.  https://matrix.hackage.haskell.org/package/sqlite-simple@1550483883

I've already revised the affected release via https://hackage.haskell.org/package/direct-sqlite-2.3.24/revisions/

You can inspect the resulting build-report matrix over at https://matrix.hackage.haskell.org/package/direct-sqlite@1550518781

There's no immediate need for action as the metadata has been corrected already on Hackage. But please either adapt the version bound for future releases (or restore compatibility with pre-GHC 7.10) to avoid this regression repeating with the next release of `direct-sqlite`.

Please let me know if you have any questions.

**Comment by sigrlami** [comment]
@hvr thanks for noticing. I'll address this in future releases.
