### ISSUE TITLE
Upgrade embedded SQLite library

### ISSUE THREAD

**Issue by rmanne** [IreneKnapp/direct-sqlite#84]
It seems like there's a bug when building the SQLite library on systems using gcc10.

Related links:
- https://sqlite.org/forum/forumpost/845dd0be91?t=h
- https://www.sqlite.org/src/info/04e1edd8e5821a37

**Comment by fgaz** [comment]
+1! Also for new features such as https://www.sqlite.org/stricttables.html

**Comment by jchia** [comment]
I have updated to 3.38.5. Does the problem still repro?
